'use client';
import {readShareState,shareURL} from '@/lib/share-state';
import {useLocale,LocaleProvider} from '@/lib/locale';
import { useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { Ship,Play,Pause,RotateCcw,Expand,Route,Fuel,ArrowUpRight,Download,Info,Check,ChevronRight,MousePointer2,Waves } from 'lucide-react';
import OceanScene from '@/components/ocean/Scene';
import SourceInventory from '@/components/ocean/SourceInventory';
import VoyageReview from '@/components/ocean/VoyageReview';
import DecisionGuide from '@/components/ocean/DecisionGuide';
import Geography,{MapScene} from '@/components/ocean/Geography';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {isReplaySelection,metricKeys,normalizeReplay} from '@/lib/ocean-types';
import type {RawReplayData,ReplayData,Trace,Summary,Metric,Policy,ExportVessel,ModelContext} from '@/lib/ocean-types';
const emptyTrace:Trace=[];
const names={double_dqn:'학습형 · Double DQN',safe_stock:'잔량 기준형 · Safe Stock',price_reactive:'가격 반응형 · Price Reactive',fixed_fueling:'출발 급유형 · Fixed Fueling'};
const evidenceRoot='https://github.com/heechan9/bunkering-ai/blob/bc3293f06e4118e5d245a716b2402fe7080905b8';
const fmt=(n:number|string,d=0)=>Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
function Picker({label,value,options,onChange}:{label:string;value:string;options:string[][];onChange:(value:string)=>void}){ const {t}=useLocale();return <label className="picker"><span>{t(label)}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={t(label)}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,text])=><SelectItem key={v} value={v}>{t(text)}</SelectItem>)}</SelectContent></Select></label>}
function FuelChart({trace,index}:{trace:Trace;index:number}){ const {t}=useLocale();const vals=[1,...trace.map(r=>r[0])],path=vals.map((v,i)=>`${i===0?'M':'L'}${12+i/30*256},${90-v*72}`).join(' ');return <svg className="fuel-chart" viewBox="0 0 286 112" role="img" aria-label={t("각 단계 후 잔량 곡선. 초기 100 기준 점선은 모델의 안전선 15입니다.")}><path d="M12,18H268M12,54H268M12,90H268" stroke="#2d4b54" fill="none"/><path d="M12,79.2H268" stroke="#dca85f" strokeDasharray="4 4"/><path d={path} stroke="#c5f378" strokeWidth="2" fill="none"/><path d={`M${12+index/30*256},10V94`} stroke="#d7e9e7" strokeDasharray="2 3"/><circle cx={12+index/30*256} cy={90-vals[Math.min(index,vals.length-1)]*72} r="4" fill="#c5f378"/><text x="12" y="108">{t("출발")}</text><text x="232" y="108">{t("30단계")}</text></svg>}
function Home(){ const {t,lang,setLang}=useLocale();
 const [data,setData]=useState<ReplayData|null>(null),[failure,setFailure]=useState(''),[policy,setPolicy]=useState('double_dqn'),[ck,setCk]=useState('42'),[caseSeed,setCaseSeed]=useState('42'),[frame,setFrame]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('1'),[view,setView]=useState('geography'),[tab,setTab]=useState('geography'),[notice,setNotice]=useState(''),[exporting,setExporting]=useState(false),[region,setRegion]=useState("hormuz"),[started,setStarted]=useState(false),[cameraReset,setCameraReset]=useState(0);
 const restored=useRef(false);const [shareFallback,setShareFallback]=useState('');
 useEffect(()=>{if(!data||restored.current)return;const selection=readShareState(window.location.search);if(!selection)return;let active=true;queueMicrotask(()=>{if(!active)return;restored.current=true;const run=selection.policy==='double_dqn'?'dqn_'+selection.checkpoint:selection.policy;setPolicy(selection.policy);setCk(selection.checkpoint);setCaseSeed(selection.caseSeed);setFrame(selection.started?Math.min(selection.step,data.runs[run]?.[selection.caseSeed]?.length??0):0);setRegion(selection.region);setTab(selection.tab);setView(selection.view);setLang(selection.lang);setStarted(selection.started);setPlaying(false)});return()=>{active=false}},[data,setLang]);
 async function share(){const url=shareURL(window.location.origin,window.location.pathname,{policy,checkpoint:ck,caseSeed,step:index,region,tab,view,lang,started});try{await navigator.clipboard.writeText(url);setShareFallback('');setNotice(t('현재 선택 링크를 복사했어요. 열면 일시정지 상태로 표시됩니다.'))}catch{setShareFallback(url)}}
 const exportRef=useRef<ExportVessel>(null);const onExportReady=useCallback((fn:ExportVessel)=>{exportRef.current=fn},[]);const key=policy==='double_dqn'?'dqn_'+ck:policy;const trace=data?.runs?.[key]?.[caseSeed]||emptyTrace;const index=Math.min(Math.floor(frame),trace.length),row=index?trace[index-1]:null;const fuel=row?row[0]:1;const totals=useMemo(()=>trace.slice(0,index).reduce((a,r)=>({buy:a.buy+r[1],consume:a.consume+r[2],sci:a.sci+r[3],reward:a.reward+r[4],events:a.events+(r[1]>1e-6?1:0)}),{buy:0,consume:0,sci:0,reward:0,events:0}),[trace,index]);
 const rawViolation=!!row&&row[0]<.15,tolerantViolation=!!row&&row[0]<.15-1e-12,boundary=rawViolation&&!tolerantViolation;const ended=index>0&&index===trace.length;const exhausted=ended&&fuel<1e-9;
 useEffect(()=>{const a=new AbortController();Promise.all(['/data/replay.json','/data/research-summary.json'].map(url=>fetch(url,{signal:a.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}))).then(([d,summary])=>setData(normalizeReplay({...(d as RawReplayData),summary:(summary as {summary:RawReplayData["summary"]}).summary}))).catch(e=>{if(e.name!=='AbortError')setFailure(t("항차 기록을 불러오지 못했어요. 새로고침해 주세요."))});return()=>a.abort()},[t]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[tab]);
 useEffect(()=>{if(!playing||!trace.length||tab!=='explore')return;let last=performance.now();const t=setInterval(()=>{const now=performance.now(),delta=Math.min(now-last,100)/1000*Number(speed);last=now;if(document.hidden)return;setFrame(n=>{const next=Math.min(trace.length,n+delta);if(next>=trace.length)setPlaying(false);return next})},50);return()=>clearInterval(t)},[playing,speed,trace,tab]);
 const choosePolicy=(v:string)=>{setPolicy(v);setPlaying(false);setFrame(n=>Math.min(n,data?.runs?.[v==='double_dqn'?'dqn_'+ck:v]?.[caseSeed]?.length??30))};
 const summary=data?.summary||[];const dqn=summary.filter(r=>r.policy==='double_dqn');const avg=(f:Metric)=>dqn.reduce((a,r)=>a+Number(r[f]),0)/Math.max(1,dqn.length);const compare:Summary[]=[...summary.filter(r=>r.policy!=='double_dqn'),{policy:'double_dqn',cases:400,...Object.fromEntries(metricKeys.map(k=>[k,avg(k)])) as Record<Metric,number>}];
 const snapshot=useRef({policy,checkpoint:ck,caseSeed:Number(caseSeed),step:index,fuel,totals,tab});useEffect(()=>{snapshot.current={policy,checkpoint:ck,caseSeed:Number(caseSeed),step:index,fuel,totals,tab}});
 useEffect(()=>{const c=(document as Document & {modelContext?:ModelContext}).modelContext;if(!c?.registerTool)return;const a=new AbortController();const tools=[{name:'read_voyage_state',description:'Read the selected synthetic voyage replay and current accounting values.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>snapshot.current},{name:'configure_voyage_replay',description:'Select a recorded synthetic policy, evaluation case, and transition; this does not run a model or predict real vessel behavior.',inputSchema:{type:'object',properties:{policy:{type:'string',enum:Object.keys(names)},checkpoint:{type:'string',enum:['42','1042','2042','3042']},caseSeed:{type:'integer',minimum:42,maximum:141},step:{type:'integer',minimum:0,maximum:30}},required:['policy','checkpoint','caseSeed','step'],additionalProperties:false},execute:async (v:unknown)=>{if(!isReplaySelection(v))throw Error('Invalid replay selection');setPolicy(v.policy);setCk(v.checkpoint);setCaseSeed(String(v.caseSeed));setFrame(v.step);setStarted(true);setPlaying(false);setTab('explore');await new Promise(r=>setTimeout(r,100));return snapshot.current}}];for(const t of tools){try{Promise.resolve(c.registerTool(t,{signal:a.signal})).catch(()=>{})}catch{}}return()=>a.abort()},[]);
 async function download(){setExporting(true);try{if(!exportRef.current)throw Error();await exportRef.current();setNotice(t("선박 개념 모델을 GLB로 저장했어요. 실선 설계 모델은 아닙니다."))}catch{setNotice(t("모델 저장을 완료하지 못했어요. 3D 화면이 나타난 뒤 다시 시도해 주세요."))}finally{setExporting(false)}}
 const stage=index===0?t("출항 준비"):index<10?t("출항·초기 운항"):index<21?t("항로 중간 구간"):ended?t("도착·운항 종료"):t("도착 구간");
 return <main className="lab"><Tabs value={tab} onValueChange={v=>{setTab(v);setPlaying(false)}}><header className="topbar"><div className="brand"><span className="brand-icon"><Ship size={24}/></span><strong>{t("병커시유 ")}<span>OCEAN LAB</span></strong></div><TabsList className="main-tabs"><TabsTrigger value="geography">{t("01 항로 선택")}</TabsTrigger><TabsTrigger value="explore">{t("02 운항 체험")}</TabsTrigger><TabsTrigger value="compare">{t("03 전략 비교")}</TabsTrigger></TabsList><div className="language-switch" role="group" aria-label="Language / 언어"><button aria-pressed={lang==='ko'} onClick={()=>setLang('ko')}>한국어</button><button aria-pressed={lang==='en'} onClick={()=>setLang('en')}>English</button></div><Button variant="outline" disabled={!data} onClick={share}>{t("선택 링크 복사")}</Button><span className="status"><span/>{t("검증 기록 체험")}</span></header>
 {shareFallback&&<div className="share-fallback"><label>{t("링크를 선택해 복사하세요")}<input readOnly value={shareFallback} onFocus={e=>e.currentTarget.select()}/></label><Button variant="ghost" onClick={()=>setShareFallback('')}>{t("알림 닫기")}</Button></div>}
 <div className="journey-guide" aria-label={t("체험 순서")}><button aria-current={tab==='geography'?'step':undefined} onClick={()=>setTab('geography')}><span>1</span><strong>{t("항로 선택")}</strong><small>{t("지역과 연구 연결 확인")}</small></button><ChevronRight/><button aria-current={tab==='explore'?'step':undefined} onClick={()=>setTab('explore')}><span>2</span><strong>{t("운항 체험")}</strong><small>{t("연료와 급유를 단계별 재생")}</small></button><ChevronRight/><button aria-current={tab==='compare'?'step':undefined} onClick={()=>setTab('compare')}><span>3</span><strong>{t("연료 구매 전략 비교")}</strong><small>{t("같은 조건의 결과 확인")}</small></button></div>
 <TabsContent value="geography" className="tab-surface"><Geography region={region} onRegionChange={setRegion} onReplay={()=>{setTab("explore");setPlaying(false);setStarted(false);setFrame(0);setView("geography")}}/></TabsContent>
 <TabsContent value="explore" className="tab-surface"><div className="workspace-intro"><div><span className="context-chip">{t("선택한 지역 · ")}{region==='hormuz'?t("호르무즈 해협"):region==='suez'?t("수에즈 운하"):region==='cape'?t("희망봉"):region==='taiwan'?t("대만해협"):region==='bab'?t("바브엘만데브"):region==='dover'?t("도버해협"):t("울산항")}</span><h1>{t("선택한 해역에서 배의 이동과 급유 기록을 따라갑니다.")}</h1><p>{t("지형은 선택한 지역, 연료·지출은 검증된 30단계 합성 기록입니다. 지역을 바꿔도 실험 조건과 결과는 같습니다.")}</p></div><div className="intro-actions"><Button disabled={!data} onClick={()=>{if(!started){setStarted(true);setFrame(0);return}if(ended)setFrame(0);setPlaying(!playing)}}>{playing?<Pause size={16}/>:<Play size={16}/>} {!started?t("선택한 기록 열기"):playing?t("재생 멈추기"):t("기록 재생 시작")}</Button><Button variant="outline" onClick={()=>setTab("compare")}>{t("평균 결과 비교 ")}<ArrowUpRight size={16}/></Button></div></div><section className="workspace"><div className={"ocean "+(view==='geography'?'regional-replay':'')} id="ocean-space">{view==='geography'?<MapScene region={region} reset={cameraReset} exaggeration={8} trafficProgress={started?frame/30:0} selectedShip={0} singleShip bunkering={started&&!!row&&row[1]>1e-6} replayLabel={started?t("{0}/30 단계 · 연료 {1}{2}",index,fmt(fuel*100,1),(row?.[1]??0)>1e-6?t(" · 급유"):''):t("체험 선박 · 기록 선택 대기")}/>:<OceanScene progress={started?frame/30:0} fuel={started?fuel:1} bunkering={started&&!!row&&row[1]>1e-6} view={view} resetCamera={cameraReset} onExportReady={onExportReady}/>}
 <div className="scene-title"><p className="kicker">RECORDED VOYAGE · BASELINE</p><h2>{view==='geography'?t("선택한 해협을 지나는 배"):<>{t("하나의 항차를,")}<br/>{t("끝까지 따라가다.")}</>}</h2><p>{t("실험 기록 재생 · 기본조건 30단계")}</p></div>
 <div className="scene-tools"><Button variant="outline" size="icon" onClick={()=>setCameraReset(n=>n+1)} aria-label={t("3D 시점 초기화")}><RotateCcw/></Button><Button variant="outline" size="icon" onClick={()=>{const el=document.getElementById('ocean-space');if(document.fullscreenElement)document.exitFullscreen?.();else el?.requestFullscreen?.().catch(()=>setNotice(t("이 기기에서는 전체화면을 지원하지 않아요.")))}} aria-label={t("3D 공간 전체화면")}><Expand/></Button><Button variant="outline" size="icon" onClick={download} disabled={exporting||view==='geography'} aria-label={t("선박 3D 모델 GLB 다운로드")}><Download/></Button></div>
 <div className="scene-bottom"><div className="camera-group" role="group" aria-label={t("시점 선택")}>{([['geography',t("선택한 해역"),Waves],['route',t("개략 항로"),Route],['ship',t("선박 근접"),Ship],['tank',t("연료 탱크"),Fuel]] as const).map(([v,label,Icon])=><Button key={v} variant="ghost" aria-pressed={view===v} onClick={()=>setView(v)}><Icon/>{label}</Button>)}</div><span className="orbit-hint"><MousePointer2 size={14}/>{t("드래그 회전 · 스크롤 확대")}</span></div>
 <div className="voyage-badge"><span className={exhausted?'dot bad':'dot'}/>{!started?t("기록 선택 대기"):exhausted?t("연료 고갈 · 종료"):ended?t("항차 도착"):(row?.[1]??0)>1e-6?t("급유 이벤트"):stage}<small>{started?t("{0} / 30 단계",String(index).padStart(2,'0')):t("검증 기록")}</small></div><div className="event-explainer" aria-live="polite"><span>{!started?t("먼저 오른쪽에서 기록을 선택하세요"):index===0?t("출발할 때"):t("{0}번째 단계 · {1}",index,stage)}</span><strong>{!started?t("정책과 시장 사례를 고르면 운항이 시작됩니다."):!row?t("연료 100으로 시작합니다."):row[1]>1e-6?t("연료 {0}을 추가로 확보했습니다.",fmt(row[1]*100,1)):exhausted?t("연료가 소진되어 운항이 끝났습니다."):t("연료 {0}을 소비했습니다.",fmt(row[2]*100,1))}</strong><p>{!started?t("선박 이동은 단계 사이를 부드럽게 연결한 설명용 연출입니다."):index===0?t("아래 재생 버튼을 누르면 단계별 변화가 나타납니다."):t("지금까지 구매 {0} · 소비 {1} · 잔량 {2}",fmt(totals.buy*100,1),fmt(totals.consume*100,1),fmt(fuel*100,1))}</p></div>
 <div className="timeline"><Button className="play" size="icon" disabled={!data||!started} aria-label={playing?t("항차 일시정지"):t("항차 재생")} onClick={()=>{if(ended)setFrame(0);setPlaying(!playing)}}>{playing?<Pause/>:<Play/>}</Button><div className="timeline-track"><div className="timeline-label"><span>{started?t("{0} · 작은 점은 급유 시점",stage):t("기록을 열면 진행 단계가 나타납니다.")}</span><span>{started?t("{0} / {1} 단계",index,trace.length||30):t("대기 중")}</span></div><Slider aria-label={t("항차 단계")} value={[started?index:0]} min={0} max={trace.length||30} step={1} onValueChange={([v])=>{setFrame(v);setPlaying(false)}} disabled={!data||!started}/><div className="event-marks">{started&&trace.map((r,i)=>r[1]>1e-6?<button key={i} onClick={()=>{setFrame(i+1);setPlaying(false)}} aria-label={t("{0}번째 전이 급유 보기",i+1)} style={{left:`${(i+1)/(trace.length||30)*100}%`}}/>:null)}</div></div><Select value={speed} onValueChange={setSpeed} disabled={!started}><SelectTrigger aria-label={t("재생 속도")} className="speed"><SelectValue/></SelectTrigger><SelectContent>{['1','2','4'].map(v=><SelectItem key={v} value={v}>{v}×</SelectItem>)}</SelectContent></Select><Button variant="ghost" size="icon" disabled={!started} aria-label={t("항차 처음으로")} onClick={()=>{setFrame(0);setPlaying(false)}}><RotateCcw/></Button></div>
 <div className="scene-footnote">{view==='geography'?t("통과선·선박 크기는 설명용 · 고도 8× 강조 · 실제 항적·시간 아님. 지출·연료는 공통 합성 기록."):t("선박·항로·항만은 설명용 3D 모형입니다. 위치·속도·파도는 실험 입력이 아닙니다.")}{view==='geography'&&<> <a href='/data/terrain-attribution.txt' target='_blank' rel='noreferrer'>{t("지형 출처")}</a>{region==='suez'&&t(" · 운하 폭은 설명용으로 확대")}</>}</div></div>
 <aside className="panel"><div className="panel-title"><p className="eyebrow">{t("검증 기록 선택")}</p><span>{t("기본조건 · 30단계")}</span></div><Picker label={t("급유 방식")} value={policy} options={Object.entries(names)} onChange={v=>{choosePolicy(v);setStarted(false);setFrame(0);setView("geography")}}/><div className="pair-pickers"><Picker label={t("학습 모델")} value={ck} options={['42','1042','2042','3042'].map(v=>[v,v])} onChange={v=>{setCk(v);setPlaying(false);setStarted(false);setFrame(0);setView("geography")}}/><Picker label={t("시장 사례")} value={caseSeed} options={Array.from({length:100},(_,i)=>[String(i+42),String(i+42)])} onChange={v=>{setCaseSeed(v);setFrame(0);setPlaying(false);setStarted(false);setFrame(0);setView("geography")}}/></div>{policy!=='double_dqn'&&<p className="small-muted">{t("규칙형은 학습 모델 선택과 무관하게 같은 결과를 냅니다.")}</p>}{!started&&<div className="selection-guide"><span>{t("다음에 볼 내용")}</span><h2>{t("선택한 정책의 운항 기록을 열어보세요.")}</h2><p>{t("배의 위치, 잔여 연료, 급유 시점과 누적 구매지출 지표가 같은 단계로 움직입니다.")}</p><Button disabled={!data} onClick={()=>{setStarted(true);setFrame(0)}}><Play size={16}/>{t("이 기록으로 체험 시작")}</Button><small>{t("재생 속도는 화면 연출만 바꾸며 계산 결과는 변하지 않습니다.")}</small></div>}{started&&<>
 <div className="fuel-metric"><div><Fuel size={17}/><span>{t("현재 연료잔량")}</span><span className="unit">{t("초기 = 100")}</span></div><strong>{fmt(fuel*100,1)}<small>/ 100</small></strong><div className="fuel-meter"><span style={{width:`${fuel*100}%`}}/><i/></div><p>{t("모델의 안전선 15 ")}<span>{t("실제 톤 단위 아님")}</span></p></div>
 <div className="stat-grid"><div><span>{t("구매한 연료")}</span><strong>{fmt(totals.buy*100,1)}</strong></div><div><span>{t("급유 횟수")}</span><strong>{totals.events}<small>{t("회")}</small></strong></div><div><span>{t("소비한 연료")}</span><strong>{fmt(totals.consume*100,1)}</strong></div><div><span>{t("구매지출 지표")}</span><strong>{fmt(totals.sci/1000,1)}<small>k</small></strong></div></div>
 <p className="small-muted sci-note">{t("연료는 초기량을 100으로 환산했습니다. 지출 지표(SCI)는 실제 금액이 아니며, k는 1,000입니다.")}</p><div className="chart-heading"><span>{t("잔량 변화")}</span><span>{t("각 단계가 끝난 뒤")}</span></div><FuelChart trace={trace} index={index}/>
 <div className={'record-status '+(boundary?'boundary':tolerantViolation?'warning':'')}><Info size={17}/><div><strong>{boundary?t("수치 경계에서 발생한 미달"):tolerantViolation?t("안전선 미달 기록"):index===0?t("출발 시점"):t("안전선 이상의 잔량")}</strong><p>{boundary?t("0.1499999999999997 < 0.15로 벌점이 발생했습니다. 허용오차 재분류에서는 미달이 아닙니다."):tolerantViolation?t("전이 후 잔량이 안전선보다 낮습니다. 도착 여부와 함께 확인하세요."):t("표시된 잔량은 합성 기록입니다. 실제 선박의 안전성을 뜻하지 않습니다.")}</p></div></div>
 <div className="balance"><Check size={14}/>{t("연료수지 ")}<code>100 + {fmt(totals.buy*100,1)} − {fmt(totals.consume*100,1)} ≈ {fmt(fuel*100,1)}</code></div>{failure&&<p role="alert">{failure}</p>}{!data&&!failure&&<p role="status" className="small-muted">{t("원본 항차 기록을 불러오는 중…")}</p>}
 <Accordion type="single" collapsible className="metric-guide"><AccordionItem value="terms"><AccordionTrigger>{t("지표와 실험 조건 자세히")}</AccordionTrigger><AccordionContent><dl><dt>{t("구매지출 지표 · SCI")}</dt><dd>{t("각 급유량 × 당시 합성 가격 × 합성 환율의 합계입니다. 남은 연료의 가치는 차감하지 않습니다.")}</dd><dt>{t("연료 표시 단위")}</dt><dd>{t("원본 정규화 값 1을 화면에서 100으로 표시합니다. 실제 연료량·탱크 용량과 연결된 값이 아닙니다.")}</dd><dt>{t("학습 모델 / 시장 사례")}</dt><dd>{t("학습 모델 4개는 서로 다른 학습 seed로 만든 DQN입니다. 시장 사례 100개는 모든 급유 방식이 공유하는 평가 seed 42–141입니다.")}</dd><dt>{t("이 화면의 범위")}</dt><dd>{t("기본 소비량 0.05, 30단계의 기존 기록입니다. 단계 사이 선박 이동은 시각적 보간이며 실제 시간·속도가 아닙니다. 해협 지도·선박 형상·파도는 실험 입력이 아닙니다.")}</dd></dl></AccordionContent></AccordionItem></Accordion></>}</aside></section></TabsContent>
 <TabsContent value="compare" className="comparison"><div className="comparison-head"><div><p className="kicker">ONE ENVIRONMENT. FOUR POLICIES.</p><h1>{t("더 많이 사면,")}<br/>{t("더 많이 남을까?")}</h1><p>{t("도착 여부와 구매지출, 남은 연료를 나란히 비교합니다.")}</p></div><div className="evidence-stamp"><strong>4 × 100</strong><span>{t("DQN 체크포인트 × 평가 사례")}</span><small>{t("규칙 정책은 각각 100개 · 같은 시장 seed")}</small></div></div>
 <div className="comparison-cards"><article><span>{t("같은 소비량")}</span><strong>150.0</strong><p>{t("Safe Stock · DQN · 초기 연료 100 기준")}</p></article><article><span>{t("DQN의 추가 최종잔량")}</span><strong>{data?'+'+fmt((avg('final_fuel_mean')-Number(summary.find(r=>r.policy==='safe_stock')?.final_fuel_mean))*100,1):'—'}</strong><p>{t("Safe Stock 대비 · 추가 구매량과 같은 크기")}</p></article><article><span>{t("DQN의 높은 구매지출 지표")}</span><strong>{data?'+'+fmt((avg('episode_sci_mean')/Number(summary.find(r=>r.policy==='safe_stock')?.episode_sci_mean)-1)*100,2):'—'}<small>%</small></strong><p>{t("Safe Stock 대비 항차 SCI")}</p></article></div>
 <p className="table-note">{t("연료는 초기량 100 기준 · 지출은 합성 지표(SCI) · 미달률은 한 번이라도 모델의 안전선을 밑돈 사례 비율입니다.")}</p><div className="comparison-table"><Table><TableHeader><TableRow>{[t("급유 방식"),t("도착률"),t("평균 구매지출 지표"),t("구매한 연료"),t("최종잔량"),t("급유 횟수"),t("미달률 원래 / 재분류")].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{compare.map(r=><TableRow key={r.policy}><TableCell><strong>{t(names[r.policy as Policy])}</strong><small>{r.policy==='double_dqn'?t("4개 체크포인트 평균"):t("100개 사례")}</small></TableCell><TableCell>{fmt(r.success_rate*100)}%</TableCell><TableCell>{fmt(r.episode_sci_mean)}</TableCell><TableCell>{fmt(r.bunker_amount_mean*100,1)}</TableCell><TableCell>{fmt(r.final_fuel_mean*100,1)}</TableCell><TableCell>{fmt(r.bunkering_count_mean,2)}</TableCell><TableCell>{fmt(r.raw_violation_episode_rate*100)}% / {fmt(r.tolerance_1e_12_violation_episode_rate*100)}%</TableCell></TableRow>)}</TableBody></Table></div>
 <div className="interpretation"><Info/><div><h2>{t("도착 성공이 곧 비용절감은 아닙니다.")}</h2><p>{t("DQN은 더 많은 연료를 구매하고 남겼습니다. Safe Stock의 기본조건 미달 판정은 부동소수점 경계 오차에서 발생했습니다. 재분류는 기존 기록에 허용오차 10⁻¹²를 적용한 후처리이며 새 환경에서의 평가가 아닙니다.")}</p><p>{t("SCI는 합성 구매지출 지표이며 최종 재고가치를 차감하지 않습니다. 실패 정책의 낮은 지출을 경제적 우위로 해석하지 않습니다.")}</p></div></div><Button onClick={()=>{setTab('explore');setPolicy('safe_stock');setFrame(17);setStarted(true);setPlaying(false)}}>{t("Safe Stock 경계 사례 보기 ")}<ArrowUpRight/></Button>
 <DecisionGuide/><SourceInventory/><VoyageReview/>
 <Accordion type="single" collapsible className="metric-guide"><AccordionItem value="evidence"><AccordionTrigger>{t("검증 근거 · 논문 · 데이터 범위")}</AccordionTrigger><AccordionContent><dl><dt>{t("같은 100개 시장 사례를 공유합니다")}</dt><dd>{t("4개 학습 모델의 400개 평가와 규칙형 300개를 합친 700개 정책·사례 조합입니다. 서로 독립적인 시장 사례 700개가 아닙니다.")}</dd><dt>{t("기존 결과와 연결된 보충 진단")}</dt><dd>{t("원본 1,600개 항차 기록·40,120개 전이를 대조했습니다. 네 체크포인트 재실행에서 각 전이 CSV가 Windows 원본과 일치했고 학습은 수행하지 않았습니다. v3.0 코드의 기존 로컬 회귀 기록은 225개 통과입니다.")}</dd><dt>{t("현재 확인된 범위")}</dt><dd>{t("이 화면은 기본조건 30단계의 합성 기록을 재생합니다. 실제 항차의 구매·소비·잔량 자료는 아직 확보되지 않았습니다. 공개 소비율 자료와 상용 플랫폼은 후속 검토 후보이며 이 실험에 투입하지 않았습니다.")}</dd><dt>{t("안전 벌점과 가격 보상은 다릅니다")}</dt><dd>{t("Safe Stock의 항차 평균 가격우위 보상은 약 +0.007202, 안전 보상은 −0.5입니다. 원래 안전선 판정의 수치 경계 효과를 함께 해석해야 합니다.")}</dd></dl><p><a href={evidenceRoot+'/docs/submission/ack_paper_v3_0.md'} target="_blank" rel="noreferrer">{t("논문 v3.0 본문 ↗")}</a> · <a href={evidenceRoot+'/docs/technical/submission_alignment_v3_0.md'} target="_blank" rel="noreferrer">{t("검증 범위와 원본 근거 ↗")}</a> · <a href="/data/integration-review.json" target="_blank" rel="noreferrer">{t("웹 수치 대조 기록 ↗")}</a></p></AccordionContent></AccordionItem></Accordion>
 </TabsContent></Tabs><footer className="lab-footer"><span><Waves size={16}/>Bunkering-AI · Research prototype</span><span>{t("합성환경 기록 재생 · 실선 디지털 트윈·미래 예측 아님")}</span><a href={evidenceRoot+'/docs/technical/reward_diagnostics_results_4seed.md'} target="_blank" rel="noreferrer">{t("연구 근거 ")}<ArrowUpRight size={14}/></a></footer>{notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice('')} aria-label={t("알림 닫기")}>×</button></div>}</main>
}

export default function App(){return <LocaleProvider><Home/></LocaleProvider>}
