'use client';
import {useState} from 'react';
import {useLocale} from '@/lib/locale';
import {Button} from '@/components/ui/button';
import {headers,exportCSV,readCSVFile,reviewVoyages,fileDigest} from '@/lib/voyage-csv';
export default function VoyageReview(){
 const {lang}=useLocale();const en=lang==='en';
 const [rows,setRows]=useState<string[][]|null>(null),[digest,setDigest]=useState(''),[previous,setPrevious]=useState(''),[error,setError]=useState(''),[encoding,setEncoding]=useState('utf-8'),[tolerance,setTolerance]=useState('0.01'),[busy,setBusy]=useState(false);
 const [baseline,setBaseline]=useState<{rows:string[][];hash:string}|null>(null);
 function save(name:string,data:unknown[][]){const url=URL.createObjectURL(new Blob([exportCSV(data)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 let results:ReturnType<typeof reviewVoyages>=[],validation='';if(rows)try{if(!tolerance.trim())throw Error('Enter a tolerance');results=reviewVoyages(rows,Number(tolerance))}catch(e){validation=String((e as Error).message)}
 const changes=()=>{if(!baseline||!rows)return '';if(baseline.hash===digest)return en?'Same file bytes':'같은 파일 바이트';if(JSON.stringify(rows[0])!==JSON.stringify(baseline.rows[0]))return en?'Headers changed; review required':'열 구성이 변경됨 · 재검토 필요';const keys=['vessel_id','voyage_id','fuel_type'].map(k=>rows[0].indexOf(k));if(keys.some(k=>k<0))return en?'Cannot match rows':'행 연결 불가';const index=(rs:string[][])=>new Map(rs.slice(1).map(r=>[JSON.stringify(keys.map(k=>r[k])),JSON.stringify(r)]));const old=index(baseline.rows),next=index(rows);if(old.size!==baseline.rows.length-1||next.size!==rows.length-1)return en?'Duplicate keys; cannot compare rows':'중복 식별자 · 행 변경 비교 보류';let added=0,removed=0,changed=0;for(const [k,v]of next)if(!old.has(k))added++;else if(old.get(k)!==v)changed++;for(const k of old.keys())if(!next.has(k))removed++;return en?`Added ${added} · removed ${removed} · changed ${changed}`:`추가 ${added} · 삭제 ${removed} · 변경 ${changed}`};
 return <details className="voyage-review"><summary>{en?'Review voyage CSV locally':'항차 CSV 자료 검토'}</summary><p>{en?'Files stay in this browser tab. This checks reported fuel accounting, not policy performance or real-vessel safety.':'파일은 현재 브라우저 탭에서만 처리합니다. 기록된 연료수지를 검사하며 정책 성능이나 실선 안전성을 검증하지 않습니다.'}</p><p>{en?'One row per vessel, voyage and fuel. Supply must be actual. All four quantities in a row must use its declared unit; no mass/volume conversion or mixing. Use ISO times with a time-zone offset.':'선박·항차·연료별 한 행을 사용하세요. 공급량은 실제량이어야 합니다. 한 행의 잔량·급유량·소비량은 동일한 단위로 입력하며 질량·부피를 변환하거나 합산하지 않습니다. 시각은 시간대가 포함된 ISO 형식입니다.'}</p>
 <div className="review-actions"><Button variant="outline" onClick={()=>save('voyage-template.csv',[headers])}>{en?'Download blank template':'빈 양식 다운로드'}</Button><label>{en?'Encoding':'문자 인코딩'} <select value={encoding} onChange={e=>setEncoding(e.target.value)}><option value="utf-8">UTF-8</option><option value="euc-kr">CP949</option></select></label><label>{en?'Tolerance (row unit)':'수지 허용오차 (행의 단위)'} <input type="number" min="0" step="any" value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label><label>{en?'Choose CSV':'CSV 선택'} <input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');setRows(null);try{const parsed=await readCSVFile(file,encoding);const hash=await fileDigest(file);setPrevious(digest);setDigest(hash);setRows(parsed)}catch(err){setError((err as Error).message)}finally{setBusy(false);e.target.value=''}}}/></label></div>
 {busy&&<p role="status">{en?'Reading…':'읽는 중…'}</p>}{(error||validation)&&<p role="alert">{error||validation}</p>}
 {rows&&<><p>{rows.length-1} {en?'rows':'행'} · SHA-256 <code className="file-hash">{digest}</code>{previous&&<span> · {digest===previous?(en?'Unchanged since previous file':'직전 파일과 동일'):(en?'Different from previous file':'직전 파일과 다름')}</span>}</p>{baseline&&<p>{changes()}</p>}<div className="review-actions"><Button disabled={!!validation||results.some(r=>r.issues.includes('duplicate-voyage-fuel'))} variant="outline" onClick={()=>setBaseline({rows,hash:digest})}>{en?'Use as comparison baseline':'변경 비교 기준으로 지정'}</Button><Button disabled={!results.length} onClick={()=>save('voyage-review.csv',[[...headers,'review_status','balance_residual','issues','input_sha256','tolerance'],...rows.slice(1).map((r,i)=>[...headers.map(k=>r[rows[0].indexOf(k)]),results[i]?.status,results[i]?.residual,results[i]?.issues.join(';'),digest,tolerance])])}>{en?'Download review CSV':'검토 결과 CSV 다운로드'}</Button><Button variant="ghost" onClick={()=>{setRows(null);setBaseline(null);setDigest('');setPrevious('');setError('')}}>{en?'Clear files':'자료 지우기'}</Button></div><p>{en?'Statuses: balanced = within entered tolerance; review = discrepancy; held = required information missing or invalid. Only the first 100 rows are previewed.':'상태: balanced는 입력한 허용오차 내 일치, review는 수지 차이 확인 필요, held는 필수 정보 미확인·오류입니다. 미리보기는 처음 100행입니다.'}</p><div className="review-table"><table><thead><tr>{['row','status','residual','issues'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{results.slice(0,100).map(r=><tr key={r.row}><td>{r.row}</td><td>{r.status}</td><td>{r.residual??'—'}</td><td>{r.issues.join(', ')||'—'}</td></tr>)}</tbody></table></div></>}
 </details>
}
